name: Container Image

on:
  # 一旦は手動実行にしておく
  # 自動だと Renovate でマージされるごとに走ってしまうので（そこまで頻繁に欲しくはない）
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_push:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup ko
        uses: ko-build/setup-ko@v0.7

      - name: Get commit short sha
        id: get_sha_short
        run: |
          echo "sha_short=$(git rev-parse --short HEAD)" >> ${GITHUB_OUTPUT}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: front/.tool-versions

      - name: Install Dependencies
        run: npm install --frozen-lockfile
        working-directory: front/

      - name: Build frontend
        run: |
          make front-build

      # ghcr.io/cuteip/eyeroute:${commit_sha_short} なイメージを作成
      - name: Build and push (cmd/eyeroute)
        run: |
          KO_DOCKER_REPO=ghcr.io/${{ github.repository_owner }} \
          ko build \
          --base-import-paths \
          --tags ${{ steps.get_sha_short.outputs.sha_short }} \
          ./cmd/eyeroute

      # ghcr.io/cuteip/eyeroute-cli:${commit_sha_short} なイメージを作成
      - name: Build and push (cmd/eyeroute-cli)
        run: |
          KO_DOCKER_REPO=ghcr.io/${{ github.repository_owner }} \
          ko build \
          --base-import-paths \
          --tags ${{ steps.get_sha_short.outputs.sha_short }} \
          ./cmd/eyeroute-cli
