name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  frontend:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions

      - name: Install Dependencies
        run: npm install --frozen-lockfile

      - name: run lint
        run: npm run lint
